import React from "react";

const PINK = "#e8185d";

export default function TermsOfUse() {
  return (
    <div style={{ maxWidth:760, margin:"0 auto", padding:"64px 24px 80px", fontFamily:"'Plus Jakarta Sans',sans-serif", color:"#1f2937" }}>
      <p style={{ fontSize:11, fontWeight:700, color:PINK, letterSpacing:"0.08em", textTransform:"uppercase", marginBottom:8 }}>Legal</p>
      <h1 style={{ fontSize:32, fontWeight:800, letterSpacing:"-0.03em", marginBottom:8 }}>Terms of Use</h1>
      <p style={{ fontSize:13, color:"#9ca3af", marginBottom:36 }}>Last updated: June 2026</p>

      <div style={{ fontSize:14.5, lineHeight:1.8, color:"#374151" }}>
        <p style={{ marginBottom:20 }}>
          By creating an account or using any Nugens product (Gen-E AI, HyperX, DigiHub, Units),
          you agree to these Terms of Use.
        </p>

        <h3 style={{ fontSize:17, fontWeight:700, marginTop:32, marginBottom:10 }}>1. Eligibility</h3>
        <p style={{ marginBottom:16 }}>
          You must be at least 18 years old, or have parental/guardian consent, to use the Platform.
        </p>

        <h3 style={{ fontSize:17, fontWeight:700, marginTop:32, marginBottom:10 }}>2. Your Account</h3>
        <p style={{ marginBottom:16 }}>
          You are responsible for maintaining the confidentiality of your login credentials and for
          all activity under your account. Notify us immediately of any unauthorized use.
        </p>

        <h3 style={{ fontSize:17, fontWeight:700, marginTop:32, marginBottom:10 }}>3. Subscriptions & Payments</h3>
        <p style={{ marginBottom:16 }}>
          Paid plans are billed in INR via Razorpay. Subscriptions renew automatically unless
          cancelled before the renewal date. Refunds are handled per our refund policy — contact{" "}
          <a href="mailto:support@nugens.in" style={{ color:PINK }}>support@nugens.in</a> within
          7 days of a charge if premium features were not used.
        </p>

        <h3 style={{ fontSize:17, fontWeight:700, marginTop:32, marginBottom:10 }}>4. Acceptable Use</h3>
        <p style={{ marginBottom:12 }}>You agree not to:</p>
        <ul style={{ paddingLeft:20, marginBottom:16 }}>
          <li>Use the Platform for unlawful, fraudulent, or harmful purposes</li>
          <li>Attempt to reverse-engineer, scrape, or overload our systems</li>
          <li>Share your account credentials with others or resell access</li>
          <li>Upload content that infringes intellectual property or violates others' rights</li>
        </ul>

        <h3 style={{ fontSize:17, fontWeight:700, marginTop:32, marginBottom:10 }}>5. AI-Generated Content</h3>
        <p style={{ marginBottom:16 }}>
          Resumes, marketing copy, images, and other content generated by Gen-E AI or DigiHub are
          provided as a starting point. You are responsible for reviewing and verifying accuracy
          before relying on or publishing AI-generated content.
        </p>

        <h3 style={{ fontSize:17, fontWeight:700, marginTop:32, marginBottom:10 }}>6. Intellectual Property</h3>
        <p style={{ marginBottom:16 }}>
          The Nugens name, logo, and platform design are our property. Content you create remains
          yours; you grant us a limited license to host and display it as needed to operate the
          service (e.g. displaying your posts in DigiHub Community).
        </p>

        <h3 style={{ fontSize:17, fontWeight:700, marginTop:32, marginBottom:10 }}>7. Termination</h3>
        <p style={{ marginBottom:16 }}>
          We may suspend or terminate accounts that violate these terms. You may close your account
          at any time from your Dashboard.
        </p>

        <h3 style={{ fontSize:17, fontWeight:700, marginTop:32, marginBottom:10 }}>8. Limitation of Liability</h3>
        <p style={{ marginBottom:16 }}>
          The Platform is provided "as is." Nugens is not liable for indirect damages arising from
          use of AI-generated content, third-party integrations, or service interruptions.
        </p>

        <h3 style={{ fontSize:17, fontWeight:700, marginTop:32, marginBottom:10 }}>9. Contact</h3>
        <p style={{ marginBottom:16 }}>
          Questions? Email <a href="mailto:support@nugens.in" style={{ color:PINK }}>support@nugens.in</a>.
        </p>
      </div>
    </div>
  );
}