/**
 * Gen-E — Export Chat to PDF
 * Converts the active chat session to a downloadable branded PDF.
 * Uses html2canvas + browser print-to-PDF approach (no external lib needed).
 */
import React, { useState } from "react";

const PINK = "#e8185d";

export default function ExportChatButton({ chat, profile }) {
  const [exporting, setExporting] = useState(false);

  const exportPDF = async () => {
    if (!chat?.messages?.length) return;
    setExporting(true);

    try {
      // Build styled HTML for the export
      const msgs = chat.messages.filter(m => m.text && m.text.trim());
      const lines = msgs.map(m => {
        const isUser = m.role === "user";
        return `
          <div style="margin-bottom:20px;display:flex;justify-content:${isUser?"flex-end":"flex-start"}">
            ${!isUser ? `<div style="width:28px;height:28px;border-radius:8px;background:#e8185d;display:flex;align-items:center;justify-content:center;font-weight:900;font-size:9px;color:white;flex-shrink:0;margin-right:10px;margin-top:2px;letter-spacing:-0.03em">GE</div>` : ""}
            <div style="max-width:80%;padding:12px 16px;border-radius:14px;font-size:13px;line-height:1.7;
              background:${isUser?"#e8185d":"#f9fafb"};
              color:${isUser?"white":"#374151"};
              border:${isUser?"none":"1px solid #f3f4f6"};
              border-bottom-${isUser?"right":"left"}-radius:4px">
              ${m.text.replace(/\n/g,"<br/>").replace(/\*\*(.+?)\*\*/g,"<strong>$1</strong>")}
            </div>
            ${isUser ? `<div style="width:28px;height:28px;border-radius:50%;background:#e8185d22;display:flex;align-items:center;justify-content:center;font-size:11px;font-weight:700;color:#e8185d;flex-shrink:0;margin-left:10px;margin-top:2px">${(profile?.full_name||"U").charAt(0).toUpperCase()}</div>` : ""}
          </div>`;
      }).join("");

      const html = `
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="UTF-8"/>
          <title>${chat.title || "Gen-E Chat"}</title>
          <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet"/>
          <style>
            *{box-sizing:border-box;margin:0;padding:0}
            body{font-family:'Plus Jakarta Sans',sans-serif;background:#fff;color:#111;padding:48px;max-width:760px;margin:0 auto}
            @media print {
              body{padding:20px}
              .no-print{display:none}
            }
          </style>
        </head>
        <body>
          <!-- Header -->
          <div style="display:flex;align-items:center;justify-content:space-between;padding-bottom:20px;border-bottom:2px solid #f0f0f0;margin-bottom:32px">
            <div>
              <div style="font-size:22px;font-weight:900;letter-spacing:-0.04em;color:#111">GEN<span style="color:#e8185d">-E</span></div>
              <div style="font-size:11px;color:#aaa;margin-top:2px;text-transform:uppercase;letter-spacing:0.06em">AI Career Intelligence</div>
            </div>
            <div style="text-align:right">
              <div style="font-size:13px;font-weight:600;color:#374151">${chat.title || "Chat Export"}</div>
              <div style="font-size:11px;color:#aaa;margin-top:2px">${new Date().toLocaleDateString("en-IN",{day:"numeric",month:"long",year:"numeric"})}</div>
              ${profile?.full_name ? `<div style="font-size:11px;color:#aaa">${profile.full_name}</div>` : ""}
            </div>
          </div>

          <!-- Messages -->
          <div>${lines}</div>

          <!-- Footer -->
          <div style="margin-top:40px;padding-top:20px;border-top:1px solid #f0f0f0;text-align:center">
            <div style="font-size:11px;color:#ccc">Generated by Gen-E AI · nugens.in.net · ${new Date().toLocaleDateString()}</div>
          </div>

          <script>window.onload=()=>setTimeout(()=>window.print(),400)</script>
        </body>
        </html>`;

      const blob = new Blob([html], { type: "text/html" });
      const url  = URL.createObjectURL(blob);
      const win  = window.open(url, "_blank");
      if (!win) {
        // Fallback: download the HTML file directly
        const a = document.createElement("a");
        a.href = url;
        a.download = `${(chat.title||"gene-chat").replace(/[^a-z0-9]/gi,"_").toLowerCase()}.html`;
        a.click();
      }
      setTimeout(() => URL.revokeObjectURL(url), 5000);
    } catch(e) {
      alert("Export failed: " + e.message);
    } finally {
      setExporting(false);
    }
  };

  return (
    <button
      onClick={exportPDF}
      disabled={exporting || !chat?.messages?.length}
      title="Export this chat as PDF"
      style={{
        display:"inline-flex", alignItems:"center", gap:5,
        padding:"5px 12px",
        background:exporting?"#f0f2f5":"#f0fdf4",
        border:exporting?"1px solid #e5e7eb":"1px solid #86efac",
        borderRadius:8, fontSize:11.5, fontWeight:700,
        color:exporting?"#aaa":"#15803d",
        cursor:exporting?"not-allowed":"pointer",
        transition:"all 0.13s", fontFamily:"inherit",
      }}
      onMouseEnter={e => { if(!exporting) { e.currentTarget.style.background="#dcfce7"; }}}
      onMouseLeave={e => { if(!exporting) { e.currentTarget.style.background="#f0fdf4"; }}}
    >
      {exporting ? "⏳ Exporting…" : "📄 Export Chat"}
    </button>
  );
}
